formatVersion: 1
formatType: am-configuration
---
# basic AM functionality - the builtin apps are in 'apps'.

applications:
  builtinAppsManifestDir: "CenterConsole/apps"

# QML apps will be able to import from modules...

runtimes:
  qml:
    importPaths: [ "imports/shared", "qml" ]

# ... as well as the SystemUI

ui:
  fullscreen: yes
  mainQml: "Main.qml"
  importPaths: [ "imports/shared", "imports/system", "qml" ]
  windowIcon: "imports/shared/assets/icons/active/apps@96.png"

systemProperties:
    public:
        styleConfig: "auto"
        showCluster: yes
    private:
        appStoreServerUrl: 'http://chaos.pelagicore.net:8080'

# development setup: no security

flags:
  noSecurity: yes
  noUiWatchdog: yes

